/*
 * FatBoss cosmetics for the legacy mod cgame.
 *
 * Client side only. This cgame ships in a zzz_fatboss_*.pk3 next to the
 * official legacy_v*.pk3, so the server keeps running the official qagame.
 * Nothing here may change playerState, prediction or input: it only moves
 * the first-person viewmodel.
 *
 * The weapon inspect is the Defender inspect (Colt, Thompson, Allied knife)
 * made data driven, with profiles for the Axis weapons and the rifles.
 * Viewmodel numbers come from the shipped models (see gen_inspect.py in the
 * FatBoss tools); Colt, Thompson and KABAR values are Defender's own.
 */

#include "cg_local.h"

#define FATBOSS_CGAME_VERSION "b3"

#define FB_INSPECT_IN_TIME    350
#define FB_INSPECT_OUT_TIME   350
#define FB_INSPECT_MAX_POINTS ((W_MAX_PARTS + 1) * 8)

typedef enum
{
	FB_STYLE_PISTOL,
	FB_STYLE_SMG,
	FB_STYLE_RIFLE,
	FB_STYLE_KNIFE
} fbInspectStyle_t;

/**
 * Open end of a sleeve or forearm, in the frame of the model attached at tag.
 * The fit keeps these points past the right or bottom screen edge.
 */
typedef struct
{
	const char *tag;
	const vec3_t *points;
	int numPoints;
} fbRim_t;

typedef struct
{
	int weapons[4];                 ///< 0 terminated
	fbInspectStyle_t style;
	qboolean hasBody;               ///< the main model holds gun surfaces, bounded below
	vec3_t bodyMins, bodyMaxs;      ///< gun surfaces only: main models also hold the forearm
	int fitParts;                   ///< bit per weapon part included in the fit
	const vec3_t *blade;            ///< knives: oriented box of the blade part (8 corners)
	vec3_t bladeAxis0;              ///< knives: blade length axis in the hand frame
	vec3_t bladeAxis1;              ///< knives: blade thickness axis in the hand frame
	float fitX, fitY;               ///< share of the half screen the weapon may use
	float roll;                     ///< model-only screen roll, forearm towards the bottom
	int holdTime;
	fbRim_t rims[2];
	int hideParts;                  ///< support hand parts hidden: the weapon is shown in one hand
	const char *oneHandSkin[2];     ///< main-model skin hiding a support hand held in the main model (axis, allied)
	vec3_t wristAxis;               ///< knives: forearm (sleeve) axis in the main model's frame
	vec3_t wristPivot;              ///< knives: wrist point on that axis
	qboolean stableFit;             ///< frame once at the start; the weapon then only turns in place
} fbInspectProfile_t;

// Generated by gen_inspect.py from the ET: Legacy 2.86.0 viewmodels.
static const vec3_t fbRim_luger_hand[] =
{
	{ -3.656250f, -15.875000f, -15.265625f },
	{ -3.265625f, -16.484375f, -18.093750f },
	{ -2.812500f, -16.796875f, -11.968750f },
	{ -1.671875f, -19.531250f, -19.500000f },
	{ -1.562500f, -18.218750f, -9.890625f },
	{ 0.046875f, -21.171875f, -18.687500f },
	{ 0.515625f, -20.671875f, -10.296875f },
	{ 1.140625f, -22.765625f, -15.515625f },
	{ 1.218750f, -22.265625f, -12.578125f }
};
static const vec3_t fbRim_silencer_hand[] =
{
	{ -6.156250f, -12.234375f, -19.906250f },
	{ -5.781250f, -16.640625f, -16.046875f },
	{ -5.765625f, -8.250000f, -15.500000f },
	{ -5.734375f, -8.875000f, -18.375000f },
	{ -5.703125f, -14.593750f, -19.171875f },
	{ -5.671875f, -9.609375f, -12.265625f },
	{ -5.500000f, -11.562500f, -10.250000f },
	{ -5.484375f, -16.375000f, -13.093750f },
	{ -5.187500f, -14.750000f, -10.750000f }
};
static const vec3_t fbRim_garand_right[] =
{
	{ -34.703125f, -6.281250f, 6.765625f },
	{ -34.531250f, -7.000000f, 7.046875f },
	{ -34.515625f, -4.906250f, 7.234375f },
	{ -34.468750f, -2.406250f, 9.687500f },
	{ -34.421875f, -7.343750f, 7.609375f },
	{ -34.421875f, -3.046875f, 8.671875f },
	{ -34.343750f, -3.796875f, 7.796875f },
	{ -34.281250f, -2.562500f, 10.750000f },
	{ -34.093750f, -3.015625f, 11.437500f },
	{ -33.734375f, -3.890625f, 11.281250f },
	{ -33.562500f, -6.687500f, 9.234375f },
	{ -33.359375f, -5.343750f, 10.593750f }
};
static const vec3_t fbRim_garand_left[] =
{
	{ -29.015625f, 5.046875f, 14.656250f },
	{ -28.640625f, 4.687500f, 15.343750f },
	{ -28.578125f, 5.812500f, 14.281250f },
	{ -27.968750f, 4.656250f, 16.171875f },
	{ -27.656250f, 7.171875f, 14.109375f },
	{ -27.062500f, 5.328125f, 16.625000f },
	{ -26.593750f, 8.609375f, 14.812500f },
	{ -26.234375f, 6.078125f, 16.953125f },
	{ -25.812500f, 7.234375f, 17.203125f },
	{ -25.781250f, 9.546875f, 16.328125f },
	{ -25.453125f, 9.265625f, 16.859375f },
	{ -25.421875f, 8.625000f, 17.296875f }
};
static const vec3_t fbRim_kar98_left[] =
{
	{ -4.453125f, 16.359375f, -11.843750f },
	{ -4.109375f, 16.921875f, -11.296875f },
	{ -3.937500f, 16.156250f, -12.625000f },
	{ -3.421875f, 17.703125f, -11.000000f },
	{ -2.875000f, 16.250000f, -13.890625f },
	{ -2.453125f, 18.250000f, -11.453125f },
	{ -1.656250f, 17.218750f, -15.000000f },
	{ -1.546875f, 18.703125f, -12.031250f },
	{ -0.984375f, 19.187500f, -13.046875f },
	{ -0.718750f, 18.859375f, -15.484375f },
	{ -0.437500f, 19.593750f, -14.343750f },
	{ -0.421875f, 19.296875f, -15.062500f }
};
static const vec3_t fbRim_kar98_right[] =
{
	{ -34.703125f, -6.281250f, 6.765625f },
	{ -34.531250f, -7.000000f, 7.046875f },
	{ -34.515625f, -4.906250f, 7.234375f },
	{ -34.468750f, -2.406250f, 9.687500f },
	{ -34.421875f, -7.343750f, 7.609375f },
	{ -34.421875f, -3.046875f, 8.671875f },
	{ -34.343750f, -3.796875f, 7.796875f },
	{ -34.281250f, -2.562500f, 10.750000f },
	{ -34.093750f, -3.015625f, 11.437500f },
	{ -33.734375f, -3.890625f, 11.281250f },
	{ -33.562500f, -6.687500f, 9.234375f },
	{ -33.359375f, -5.343750f, 10.593750f }
};
static const vec3_t fbBlade_knife[] =
{
	{ -13.250091f, -4.601770f, 3.798479f },
	{ 8.536194f, 6.416463f, 0.922322f },
	{ -11.204763f, -9.510108f, 0.488117f },
	{ 10.581522f, 1.508126f, -2.388039f },
	{ -12.676242f, -5.353093f, 5.267036f },
	{ 9.110044f, 5.665140f, 2.390879f },
	{ -10.630914f, -10.261430f, 1.956674f },
	{ 11.155371f, 0.756803f, -0.919483f }
};
#define FB_KNIFE_AXIS0 { 0.895470f, 0.019324f, 0.444702f }
#define FB_KNIFE_AXIS1 { 0.205926f, -0.903700f, -0.375393f }

static const vec3_t fbRim_mp40_left[] =
{
	{ -20.906250f, 20.484375f, -3.437500f },
	{ -20.859375f, 20.750000f, -5.718750f },
	{ -20.281250f, 21.109375f, -1.609375f },
	{ -20.171875f, 21.046875f, -6.328125f },
	{ -19.296875f, 21.578125f, -6.546875f },
	{ -19.296875f, 22.312500f, -0.671875f },
	{ -18.593750f, 23.156250f, -0.453125f },
	{ -18.031250f, 22.203125f, -5.718750f },
	{ -17.687500f, 23.531250f, -1.203125f },
	{ -17.109375f, 22.687500f, -4.812500f },
	{ -16.937500f, 23.250000f, -3.703125f },
	{ -16.921875f, 23.734375f, -2.437500f }
};

// Defender's Colt data: padded bounds of w_colt_new and the w_hand rim.
static const vec3_t fbRim_colt_hand[] =
{
	{  2.468750f, -20.125000f, -18.000000f },
	{  3.500000f, -21.640625f, -15.000000f },
	{  3.578125f, -21.156250f, -12.218750f },
	{  2.906250f, -19.656250f, -10.062500f },
	{  0.968750f, -17.343750f,  -9.687500f },
	{ -0.218750f, -16.000000f, -11.656250f },
	{ -1.015625f, -15.125000f, -14.750000f },
	{ -0.640625f, -15.703125f, -17.437500f },
	{  0.859375f, -18.578125f, -18.765625f }
};

// Defender's Thompson viewmodel: the right sleeve added to the main model
// (shipped in the FatBoss pk3).
static const vec3_t fbRim_thompson_right[] =
{
	{ -24.843750f, -12.203125f, -10.828125f },
	{ -25.031250f, -11.531250f, -12.750000f },
	{ -25.328125f, -10.046875f, -14.187500f },
	{ -25.625000f,  -7.765625f, -13.546875f },
	{ -25.593750f,  -7.156250f, -11.437500f },
	{ -25.406250f,  -6.562500f,  -7.937500f },
	{ -25.171875f,  -7.125000f,  -5.953125f },
	{ -24.921875f, -10.015625f,  -6.031250f },
	{ -24.781250f, -11.937500f,  -8.953125f }
};

// Defender's knife data: the shared knife sleeve end and a tight KABAR blade box.
static const vec3_t fbRim_knife_sleeve[] =
{
	{ -29.484375f, -2.625000f, -5.468750f },
	{ -29.468750f, -0.968750f, -3.390625f },
	{ -29.250000f, -0.031250f, -1.031250f },
	{ -28.515625f, -0.968750f,  1.250000f },
	{ -27.875000f, -2.843750f,  3.390625f },
	{ -27.015625f, -4.890625f,  4.234375f },
	{ -26.062500f, -7.750000f,  4.187500f }
};

static const vec3_t fbBlade_kabar[] =
{
	{   9.545370f,   5.069296f,  2.534371f },
	{  11.205991f,   1.092460f, -0.421931f },
	{   8.563741f,   6.333348f,  0.282558f },
	{  10.224362f,   2.356511f, -2.673744f },
	{ -13.089943f,  -6.775174f,  5.752864f },
	{ -11.429322f, -10.752010f,  2.796562f },
	{ -14.071571f,  -5.511122f,  3.501051f },
	{ -12.410950f,  -9.487959f,  0.544749f }
};

#define FB_RIM(tag, points) { tag, points, ARRAY_LEN(points) }
#define FB_PART(n)          (1 << (n))

static const fbInspectProfile_t fbInspectProfiles[] =
{
	{
		{ WP_COLT, 0 }, FB_STYLE_PISTOL,
		qtrue, { 19.5f, -5.9f, -14.8f }, { 37.3f, -2.5f, -1.8f },
		FB_PART(0) | FB_PART(1) | FB_PART(2) | FB_PART(4),
		NULL, { 0 }, { 0 }, 0.60f, 0.70f, 35.0f, 3000,
		{ FB_RIM("tag_weapon", fbRim_colt_hand) },
		FB_PART(3), { NULL, NULL }, { 0 }, { 0 }
	},
	{
		{ WP_SILENCED_COLT, 0 }, FB_STYLE_PISTOL,
		qtrue, { 19.5f, -5.9f, -14.8f }, { 37.3f, -2.5f, -1.8f },
		FB_PART(0) | FB_PART(1) | FB_PART(2) | FB_PART(4) | FB_PART(5),
		NULL, { 0 }, { 0 }, 0.60f, 0.70f, 35.0f, 3000,
		{ FB_RIM("tag_weapon", fbRim_colt_hand) },
		FB_PART(3) | FB_PART(6), { NULL, NULL }, { 0 }, { 0 }
	},
	{
		{ WP_LUGER, 0 }, FB_STYLE_PISTOL,
		qtrue, { 18.3f, -6.6f, -16.8f }, { 36.5f, -1.6f, -1.8f },
		FB_PART(0) | FB_PART(1) | FB_PART(2),
		NULL, { 0 }, { 0 }, 0.60f, 0.70f, 35.0f, 3000,
		{ FB_RIM("tag_weapon", fbRim_luger_hand) },
		// refitting every frame made the luger pump in and out while it turned
		FB_PART(3), { NULL, NULL }, { 0 }, { 0 }, qtrue
	},
	{
		{ WP_SILENCER, 0 }, FB_STYLE_PISTOL,
		qtrue, { 18.3f, -6.6f, -16.8f }, { 36.5f, -1.6f, -1.8f },
		FB_PART(0) | FB_PART(1) | FB_PART(2) | FB_PART(4),
		NULL, { 0 }, { 0 }, 0.60f, 0.70f, 35.0f, 3000,
		{ FB_RIM("tag_weapon", fbRim_silencer_hand) },
		FB_PART(3) | FB_PART(5), { NULL, NULL }, { 0 }, { 0 }, qtrue
	},
	{
		{ WP_THOMPSON, 0 }, FB_STYLE_SMG,
		qtrue, { 6.0f, -3.75f, -6.7f }, { 30.55f, -0.9f, 2.45f },
		FB_PART(0) | FB_PART(1),
		NULL, { 0 }, { 0 }, 0.66f, 0.66f, 20.0f, 5000,
		{ FB_RIM("tag_weapon", fbRim_thompson_right) },
		FB_PART(2), { NULL, NULL }, { 0 }, { 0 }
	},
	{
		{ WP_MP40, 0 }, FB_STYLE_SMG,
		qtrue, { 7.5f, -5.5f, -12.4f }, { 39.2f, -1.3f, 3.2f },
		FB_PART(0) | FB_PART(1),
		NULL, { 0 }, { 0 }, 0.66f, 0.66f, 20.0f, 5000,
		// the MP40 viewmodel has one hand only, under the gun: keep it
		{ FB_RIM("tag_barrel3", fbRim_mp40_left) },
		0, { NULL, NULL }, { 0 }, { 0 }
	},
	{
		// the left hand is hidden, the right hand holds the grip
		{ WP_CARBINE, 0 }, FB_STYLE_RIFLE,
		qtrue, { -2.3f, -9.5f, -5.0f }, { 83.9f, -2.3f, 11.8f },
		FB_PART(0) | FB_PART(3) | FB_PART(5),
		NULL, { 0 }, { 0 }, 0.85f, 0.62f, 8.0f, 5000,
		{ FB_RIM("tag_barrel3", fbRim_garand_right) },
		FB_PART(4), { NULL, NULL }, { 0 }, { 0 }
	},
	{
		// the game already hides the right hand with the launcher: the left one holds it
		{ WP_M7, 0 }, FB_STYLE_RIFLE,
		qtrue, { -2.3f, -9.5f, -5.0f }, { 83.9f, -2.3f, 11.8f },
		FB_PART(0) | FB_PART(1) | FB_PART(3) | FB_PART(5),
		NULL, { 0 }, { 0 }, 0.85f, 0.62f, 8.0f, 5000,
		{ FB_RIM("tag_barrel5", fbRim_garand_left) },
		0, { NULL, NULL }, { 0 }, { 0 }
	},
	{
		// the left hand lives in the main model: a skin hides it
		{ WP_KAR98, 0 }, FB_STYLE_RIFLE,
		qtrue, { -27.9f, -7.5f, -17.0f }, { 64.4f, 0.2f, -0.1f },
		FB_PART(0) | FB_PART(3) | FB_PART(4) | FB_PART(5),
		NULL, { 0 }, { 0 }, 0.85f, 0.62f, 8.0f, 5000,
		{ FB_RIM("tag_barrel3", fbRim_kar98_right) },
		0, { "models/fatboss/kar98/v_kar98_onehand_axis.skin", "models/fatboss/kar98/v_kar98_onehand_allied.skin" }, { 0 }, { 0 }
	},
	{
		{ WP_GPG40, 0 }, FB_STYLE_RIFLE,
		qtrue, { -27.9f, -7.5f, -17.0f }, { 64.4f, 0.2f, -0.1f },
		FB_PART(0) | FB_PART(1) | FB_PART(3) | FB_PART(4) | FB_PART(5),
		NULL, { 0 }, { 0 }, 0.85f, 0.62f, 8.0f, 5000,
		{ FB_RIM("tag_weapon", fbRim_kar98_left) },
		0, { NULL, NULL }, { 0 }, { 0 }
	},
	{
		{ WP_KNIFE_KABAR, 0 }, FB_STYLE_KNIFE,
		qfalse, { 0 }, { 0 },
		FB_PART(0),
		fbBlade_kabar, { 0.89534352f, 0.03525187f, 0.44397892f }, { 0.20137128f, -0.92119160f, -0.33294991f },
		0.58f, 0.60f, 0.0f, 5000,
		{ FB_RIM("tag_weapon", fbRim_knife_sleeve) },
		0, { NULL, NULL }, { 0.9724f, 0.2138f, -0.0939f }, { 0.61f, 3.55f, -2.42f }
	},
	{
		{ WP_KNIFE, 0 }, FB_STYLE_KNIFE,
		qfalse, { 0 }, { 0 },
		FB_PART(0),
		fbBlade_knife, FB_KNIFE_AXIS0, FB_KNIFE_AXIS1,
		0.58f, 0.60f, 0.0f, 5000,
		{ FB_RIM("tag_weapon", fbRim_knife_sleeve) },
		0, { NULL, NULL }, { 0.9724f, 0.2138f, -0.0939f }, { 0.61f, 3.55f, -2.42f }
	},
};

static struct
{
	qboolean active;
	qboolean ending;
	int startTime;
	int endTime;
	int weapon;
	float endFraction;
	const fbInspectProfile_t *profile;
	int nextShot;                   ///< fb_inspectshots: inspect time of the next screenshot
	qboolean framed;                ///< stableFit: the first frame's framing is stored
	vec3_t frameCenterCam;          ///< stableFit: weapon centre in view space
	vec3_t frameCenterModel;        ///< stableFit: weapon centre in the hand's own frame
} fbInspect;

/// review aid, off by default: screenshot every N ms of inspect game time
static vmCvar_t fb_inspectshots;

static const fbInspectProfile_t *CG_FatBoss_InspectProfile(int weapon)
{
	int i, j;

	for (i = 0; i < (int)ARRAY_LEN(fbInspectProfiles); i++)
	{
		for (j = 0; fbInspectProfiles[i].weapons[j]; j++)
		{
			if (fbInspectProfiles[i].weapons[j] == weapon)
			{
				return &fbInspectProfiles[i];
			}
		}
	}
	return NULL;
}

/**
 * @brief Only inspect an idle, supported weapon held by the local player.
 */
static qboolean CG_FatBoss_InspectAllowed(const playerState_t *ps)
{
	const fbInspectProfile_t *profile = CG_FatBoss_InspectProfile(ps->weapon);
	usercmd_t                cmd;

	if (!profile || !cg.snap || cg.demoPlayback || cg.renderingThirdPerson
	    || cg.editingSpeakers || cg.testGun || cg.showGameView || cgs.dbShowing
	    || (cg_drawGun.integer != 1 && !(cg_drawGun.integer == 2 && profile->style == FB_STYLE_KNIFE))
	    || ps->pm_type != PM_NORMAL
	    || ps->stats[STAT_HEALTH] <= 0
	    || ps->persistant[PERS_TEAM] == TEAM_SPECTATOR
	    || (ps->pm_flags & (PMF_FOLLOW | PMF_LIMBO))
	    || (ps->eFlags & (EF_FIRING | EF_MG42_ACTIVE | EF_AAGUN_ACTIVE | EF_MOUNTEDTANK | EF_PRONE_MOVING))
	    || ps->persistant[PERS_HWEAPON_USE]
	    || cg.zoomed || cg.zoomedBinoc || cg.zoomval != 0.0f
	    || cg.weapzoomActive || cg.binocZoomTime
	    || ps->weaponstate != WEAPON_READY || cg.weaponSelect != ps->weapon)
	{
		return qfalse;
	}

	// cancel before prediction enters a firing or reload state, never consume input
	if (trap_GetUserCmd(trap_GetCurrentCmdNumber(), &cmd)
	    && ((cmd.buttons & BUTTON_ATTACK) || (cmd.wbuttons & (WBUTTON_RELOAD | WBUTTON_ATTACK2))))
	{
		return qfalse;
	}

	return qtrue;
}

static float CG_FatBoss_Ease(float fraction)
{
	if (fraction <= 0.0f)
	{
		return 0.0f;
	}
	if (fraction >= 1.0f)
	{
		return 1.0f;
	}
	return fraction * fraction * (3.0f - 2.0f * fraction);
}

static int CG_FatBoss_InspectElapsed(void)
{
	return (fbInspect.ending ? fbInspect.endTime : cg.time) - fbInspect.startTime;
}

/**
 * @brief The pose comes from time only, so it does not depend on render pass count.
 */
static float CG_FatBoss_InspectFraction(void)
{
	int elapsed, hold;

	if (!fbInspect.active || !fbInspect.profile)
	{
		return 0.0f;
	}
	if (fbInspect.ending)
	{
		elapsed = cg.time - fbInspect.endTime;
		return fbInspect.endFraction * (1.0f - CG_FatBoss_Ease((float)elapsed / FB_INSPECT_OUT_TIME));
	}

	hold    = fbInspect.profile->holdTime;
	elapsed = cg.time - fbInspect.startTime;
	if (elapsed < FB_INSPECT_IN_TIME)
	{
		return CG_FatBoss_Ease((float)elapsed / FB_INSPECT_IN_TIME);
	}
	if (elapsed < FB_INSPECT_IN_TIME + hold)
	{
		return 1.0f;
	}
	return 1.0f - CG_FatBoss_Ease((float)(elapsed - FB_INSPECT_IN_TIME - hold) / FB_INSPECT_OUT_TIME);
}

/**
 * @brief +ilookatweapon: start the inspect, or ease back on a second press.
 */
void CG_FatBoss_Inspect_f(void)
{
	if (fbInspect.active)
	{
		if (!fbInspect.ending)
		{
			fbInspect.endFraction = CG_FatBoss_InspectFraction();
			fbInspect.endTime     = cg.time;
			fbInspect.ending      = qtrue;
		}
		return;
	}
	if (!CG_FatBoss_InspectAllowed(&cg.predictedPlayerState))
	{
		return;
	}

	fbInspect.active    = qtrue;
	fbInspect.ending    = qfalse;
	fbInspect.startTime = cg.time;
	fbInspect.weapon    = cg.predictedPlayerState.weapon;
	fbInspect.profile   = CG_FatBoss_InspectProfile(fbInspect.weapon);
	fbInspect.nextShot  = 0;
	fbInspect.framed    = qfalse;
}

/**
 * @brief -ilookatweapon: registered so the key release is not sent to the server.
 */
void CG_FatBoss_InspectUp_f(void)
{
}

void CG_FatBoss_CancelInspect(void)
{
	fbInspect.active = qfalse;
	fbInspect.ending = qfalse;
}

/**
 * @brief Gameplay actions end the inspect at once; a finished one eases out.
 */
void CG_FatBoss_UpdateInspect(const playerState_t *ps)
{
	if (!fbInspect.active)
	{
		return;
	}
	trap_Cvar_Update(&fb_inspectshots);
	if (fb_inspectshots.integer > 0 && cg.time - fbInspect.startTime >= fbInspect.nextShot)
	{
		CG_Printf("FBSHOT %d %d\n", fbInspect.weapon, fbInspect.nextShot);
		trap_SendConsoleCommand("screenshotJPEG\n");
		fbInspect.nextShot += fb_inspectshots.integer;
	}
	if (!CG_FatBoss_InspectAllowed(ps) || ps->weapon != fbInspect.weapon
	    || cg.time < fbInspect.startTime
	    || (fbInspect.ending && cg.time - fbInspect.endTime >= FB_INSPECT_OUT_TIME)
	    || (!fbInspect.ending && cg.time - fbInspect.startTime
	        >= FB_INSPECT_IN_TIME + fbInspect.profile->holdTime + FB_INSPECT_OUT_TIME))
	{
		CG_FatBoss_CancelInspect();
	}
}

/**
 * @brief Present the side, roll to examine the top, turn back, then settle.
 *
 * A manual return freezes the sequence at the button press while the overall
 * inspection blend eases out.
 */
static void CG_FatBoss_InspectAngles(vec3_t angles)
{
	typedef struct
	{
		int time;
		vec3_t angles;
	} inspectKeyframe_t;
	static const inspectKeyframe_t pistolKeyframes[] =
	{
		{    0, {  -4.0f, 70.0f, -10.0f } },
		{  700, {  -4.0f, 70.0f, -10.0f } },
		{ 1550, { -14.0f, 55.0f, -42.0f } },
		{ 2400, {   8.0f, 65.0f,  12.0f } },
		{ 3050, {  -4.0f, 70.0f, -10.0f } },
		{ 3350, {  -4.0f, 70.0f, -10.0f } }
	};
	static const inspectKeyframe_t smgKeyframes[] =
	{
		{    0, {  -7.0f, 72.0f,  -8.0f } },
		{ 1000, {  -7.0f, 72.0f,  -8.0f } },
		{ 2400, { -18.0f, 55.0f, -36.0f } },
		{ 3900, {   5.0f, 82.0f,  20.0f } },
		{ 5000, {  -7.0f, 72.0f,  -8.0f } },
		{ 5350, {  -7.0f, 72.0f,  -8.0f } }
	};
	// long guns: side on across the screen, tip the top towards the camera, turn back
	static const inspectKeyframe_t rifleKeyframes[] =
	{
		{    0, {  -4.0f, 86.0f,  -6.0f } },
		{ 1200, {  -4.0f, 86.0f,  -6.0f } },
		{ 2600, { -12.0f, 74.0f, -30.0f } },
		{ 3900, {   4.0f, 96.0f,  16.0f } },
		{ 5000, {  -4.0f, 86.0f,  -6.0f } },
		{ 5350, {  -4.0f, 86.0f,  -6.0f } }
	};
	const inspectKeyframe_t *keyframes;
	int                     numKeyframes;
	int                     elapsed = CG_FatBoss_InspectElapsed();
	int                     i, j;
	float                   fraction;

	switch (fbInspect.profile->style)
	{
	case FB_STYLE_PISTOL:
		keyframes    = pistolKeyframes;
		numKeyframes = ARRAY_LEN(pistolKeyframes);
		break;
	case FB_STYLE_RIFLE:
		keyframes    = rifleKeyframes;
		numKeyframes = ARRAY_LEN(rifleKeyframes);
		break;
	default:
		keyframes    = smgKeyframes;
		numKeyframes = ARRAY_LEN(smgKeyframes);
		break;
	}

	for (i = 1; i < numKeyframes; i++)
	{
		if (elapsed < keyframes[i].time)
		{
			fraction = CG_FatBoss_Ease((float)(elapsed - keyframes[i - 1].time)
			                           / (keyframes[i].time - keyframes[i - 1].time));
			for (j = 0; j < 3; j++)
			{
				angles[j] = keyframes[i - 1].angles[j]
				            + fraction * (keyframes[i].angles[j] - keyframes[i - 1].angles[j]);
			}
			return;
		}
	}
	VectorCopy(keyframes[numKeyframes - 1].angles, angles);
}

/**
 * @brief Wrist twist of the knife hand: turn the blade to its other face and back.
 */
static float CG_FatBoss_KnifeSpin(void)
{
	static const struct
	{
		int time;
		float spin;
	} keyframes[] =
	{
		{    0,   0.0f },
		{ 1100,   0.0f },
		{ 2100, 150.0f },
		{ 3700, 150.0f },
		{ 4700,   0.0f },
		{ 5350,   0.0f }
	};
	int   elapsed = CG_FatBoss_InspectElapsed();
	int   i;
	float fraction;

	for (i = 1; i < (int)ARRAY_LEN(keyframes); i++)
	{
		if (elapsed < keyframes[i].time)
		{
			fraction = CG_FatBoss_Ease((float)(elapsed - keyframes[i - 1].time)
			                           / (keyframes[i].time - keyframes[i - 1].time));
			return keyframes[i - 1].spin + fraction * (keyframes[i].spin - keyframes[i - 1].spin);
		}
	}
	return keyframes[ARRAY_LEN(keyframes) - 1].spin;
}

/**
 * @brief Hold the knife up with the complete blade above the hand.
 *
 * The twist (CG_FatBoss_KnifeTwist) then turns the hand about the forearm
 * axis. Turning it about the blade axis swung the sleeve around and showed
 * its hollow inside.
 */
static void CG_FatBoss_KnifeAxis(vec3_t axis[3])
{
	vec3_t source[3], sourceTranspose[3], target[3], front;
	int    i, j;

	VectorCopy(fbInspect.profile->bladeAxis0, source[0]);
	VectorCopy(fbInspect.profile->bladeAxis1, source[1]);
	VectorNormalize(source[0]);
	VectorNormalize(source[1]);
	CrossProduct(source[0], source[1], source[2]);
	for (i = 0; i < 3; i++)
	{
		for (j = 0; j < 3; j++)
		{
			sourceTranspose[i][j] = source[j][i];
		}
	}

	// a modest upward diagonal presents the complete blade above the hand
	VectorSet(target[0], 0.10f, 0.945f, 0.311f);
	VectorNormalize(target[0]);
	VectorSet(front, -1.0f, 0.0f, 0.0f);
	VectorMA(front, -DotProduct(front, target[0]), target[0], front);
	VectorNormalize(front);
	VectorCopy(front, target[1]);
	CrossProduct(target[0], target[1], target[2]);
	MatrixMultiply(sourceTranspose, target, axis);
}

/**
 * @brief Add a model's oriented bounds in the inspection's camera coordinates.
 */
static qboolean CG_FatBoss_InspectAddBounds(const refEntity_t *hand, qhandle_t model, const char *tagName,
                                            qboolean weaponBody, qboolean blade, vec3_t mins, vec3_t maxs,
                                            vec3_t *points, int *numPoints)
{
	const fbInspectProfile_t *profile = fbInspect.profile;
	orientation_t            tag;
	vec3_t                   modelMins, modelMaxs, modelOrigin, modelAxis[3], corner;
	float                    coordinate;
	int                      i, j;

	if (!model || trap_R_LerpTag(&tag, hand, tagName, 0) < 0)
	{
		return qfalse;
	}

	VectorCopy(hand->origin, modelOrigin);
	for (i = 0; i < 3; i++)
	{
		VectorMA(modelOrigin, tag.origin[i], hand->axis[i], modelOrigin);
	}
	MatrixMultiply(tag.axis, hand->axis, modelAxis);

	if (weaponBody)
	{
		// the main models also hold the forearm; fitting it would shrink the gun
		VectorCopy(profile->bodyMins, modelMins);
		VectorCopy(profile->bodyMaxs, modelMaxs);
	}
	else
	{
		trap_R_ModelBounds(model, modelMins, modelMaxs);
	}
	for (i = 0; i < 3 && !blade; i++)
	{
		// invalid renderer bounds must never expand the fit (also rejects NaNs)
		if (!(modelMins[i] <= modelMaxs[i]) || modelMins[i] < -4096.0f || modelMaxs[i] > 4096.0f)
		{
			if (fbInspect.weapon == WP_SILENCED_COLT && !Q_stricmp(tagName, "tag_barrel6"))
			{
				// the shipped silencer reports inverted bounds; these enclose its vertices
				VectorSet(modelMins, -0.1f, -2.8f, -1.45f);
				VectorSet(modelMaxs, 10.4f, 1.4f, 2.8f);
				break;
			}
			return qfalse;
		}
	}

	for (i = 0; i < 8; i++)
	{
		VectorCopy(modelOrigin, corner);
		for (j = 0; j < 3; j++)
		{
			coordinate = blade ? profile->blade[i][j] : ((i & (1 << j)) ? modelMaxs[j] : modelMins[j]);
			VectorMA(corner, coordinate, modelAxis[j], corner);
		}
		AddPointToBounds(corner, mins, maxs);
		if (*numPoints < FB_INSPECT_MAX_POINTS)
		{
			VectorCopy(corner, points[*numPoints]);
			(*numPoints)++;
		}
	}
	return qtrue;
}

/**
 * @brief Accumulate the shifts that move one sleeve's open end past an edge.
 */
static void CG_FatBoss_InspectArmLimits(const refEntity_t *hand, const fbRim_t *rim, const vec3_t origin,
                                        float tanX, float tanY, float *rightShift, float *downShift)
{
	orientation_t tag;
	vec3_t        modelOrigin, modelAxis[3], point;
	int           i, j;

	if (trap_R_LerpTag(&tag, hand, rim->tag, 0) < 0)
	{
		return;
	}
	VectorCopy(origin, modelOrigin);
	for (i = 0; i < 3; i++)
	{
		VectorMA(modelOrigin, tag.origin[i], hand->axis[i], modelOrigin);
	}
	MatrixMultiply(tag.axis, hand->axis, modelAxis);
	for (i = 0; i < rim->numPoints; i++)
	{
		VectorCopy(modelOrigin, point);
		for (j = 0; j < 3; j++)
		{
			VectorMA(point, rim->points[i][j], modelAxis[j], point);
		}
		*rightShift = MIN(*rightShift, -1.01f * point[0] * tanX - point[1]);
		*downShift  = MIN(*downShift, -1.01f * point[0] * tanY - point[2]);
	}
}

/**
 * @brief Keep the forearm's open end outside the right or bottom edge.
 */
static void CG_FatBoss_InspectHideArmEnd(const refEntity_t *hand, float tanX, float tanY,
                                         const vec3_t *points, int numPoints, vec3_t origin)
{
	vec3_t point;
	float  rightShift = 0.0f, downShift = 0.0f;
	float  rightLimit = -999999.0f, downLimit = -999999.0f;
	int    i;

	for (i = 0; i < (int)ARRAY_LEN(fbInspect.profile->rims); i++)
	{
		if (fbInspect.profile->rims[i].tag)
		{
			CG_FatBoss_InspectArmLimits(hand, &fbInspect.profile->rims[i], origin, tanX, tanY, &rightShift, &downShift);
		}
	}

	// preserve a visible border around the weapon, including its grip and magazine
	for (i = 0; i < numPoints; i++)
	{
		VectorAdd(points[i], origin, point);
		rightLimit = MAX(rightLimit, -0.95f * point[0] * tanX - point[1]);
		downLimit  = MAX(downLimit, -0.95f * point[0] * tanY - point[2]);
	}
	if (downShift >= downLimit)
	{
		origin[2] += downShift;
	}
	else if (rightShift >= rightLimit)
	{
		origin[1] += rightShift;
	}
	else
	{
		// very unusual aspect ratios may require the corner instead of one edge
		origin[1] += MIN(0.0f, MAX(rightShift, rightLimit));
		origin[2] += MIN(0.0f, MAX(downShift, downLimit));
	}
}

/**
 * @brief Compensate only the viewmodel for the world's FOV, preserving pixels.
 */
static void CG_FatBoss_InspectProjection(float *tanX, float *tanY, vec3_t scale)
{
	float aspect = (float)cg.refdef_current->width / MAX(1, cg.refdef_current->height);

	// the virtual vertical FOV is fixed; horizontal FOV follows the actual aspect
	*tanY    = 0.75f * tanf(75.0f * (float)M_PI / 360.0f);
	*tanX    = *tanY * aspect;
	scale[0] = 1.0f;
	scale[1] = tanf(Com_Clamp(5.0f, 175.0f, cg.refdef_current->fov_x) * (float)M_PI / 360.0f) / *tanX;
	scale[2] = tanf(Com_Clamp(5.0f, 175.0f, cg.refdef_current->fov_y) * (float)M_PI / 360.0f) / *tanY;
}

static void CG_FatBoss_KnifeTwist(const refEntity_t *hand, vec3_t origin, vec3_t axis[3]);

/**
 * @brief Fit the complete weapon to a bounded screen area at the actual FOV.
 */
static qboolean CG_FatBoss_InspectTarget(const refEntity_t *hand, vec3_t targetOrigin, vec3_t targetAxis[3])
{
	const fbInspectProfile_t *profile = fbInspect.profile;
	refEntity_t              localHand = *hand;
	weaponInfo_t             *weapon   = &cg_weapons[fbInspect.weapon];
	vec3_t                   angles, mins, maxs, center, extent, localOrigin, projectionScale;
	vec3_t                   presentationAxis[3], tempAxis[3], points[FB_INSPECT_MAX_POINTS];
	float                    tanX, tanY, depth, fitX, fitY;
	int                      i, j, numPoints = 0;

	if (profile->style == FB_STYLE_KNIFE)
	{
		CG_FatBoss_KnifeAxis(localHand.axis);
	}
	else
	{
		CG_FatBoss_InspectAngles(angles);
		AnglesToAxis(angles, localHand.axis);
		// a model-only screen roll points the forearm naturally toward the bottom
		VectorSet(angles, 0.0f, 0.0f, profile->roll);
		AnglesToAxis(angles, presentationAxis);
		MatrixMultiply(localHand.axis, presentationAxis, tempAxis);
		AxisCopy(tempAxis, localHand.axis);
	}
	VectorClear(localHand.origin);
	localHand.nonNormalizedAxes = qfalse;

	if (profile->stableFit && fbInspect.framed)
	{
		// keep the weapon centre where the first frame put it: only the turn changes
		for (i = 0; i < 3; i++)
		{
			localOrigin[i] = fbInspect.frameCenterCam[i];
			for (j = 0; j < 3; j++)
			{
				localOrigin[i] -= fbInspect.frameCenterModel[j] * localHand.axis[j][i];
			}
		}
		CG_FatBoss_InspectProjection(&tanX, &tanY, projectionScale);
		goto placed;
	}

	ClearBounds(mins, maxs);

	if (profile->hasBody && !CG_FatBoss_InspectAddBounds(&localHand, weapon->weaponModel[W_FP_MODEL].model,
	                                                     "tag_weapon", qtrue, qfalse, mins, maxs, points, &numPoints))
	{
		return qfalse;
	}
	for (i = W_PART_1; i < W_MAX_PARTS; i++)
	{
		if (profile->fitParts & FB_PART(i))
		{
			CG_FatBoss_InspectAddBounds(&localHand, weapon->partModels[W_FP_MODEL][i].model,
			                            weapon->partModels[W_FP_MODEL][i].tagName, qfalse,
			                            profile->blade && i == W_PART_1, mins, maxs, points, &numPoints);
		}
	}
	if (!numPoints)
	{
		return qfalse;
	}

	for (i = 0; i < 3; i++)
	{
		center[i] = 0.5f * (mins[i] + maxs[i]);
		extent[i] = 0.5f * (maxs[i] - mins[i]);
	}
	CG_FatBoss_InspectProjection(&tanX, &tanY, projectionScale);

	// include the depth extent so even the nearest corner respects the framing
	fitX  = extent[1] / (profile->fitX * tanX);
	fitY  = extent[2] / (profile->fitY * tanY);
	depth = extent[0] + MAX(8.0f, MAX(fitX, fitY));
	VectorSet(localOrigin, depth - center[0],
	          -0.08f * (depth - extent[0]) * tanX - center[1],
	          -0.20f * (depth - extent[0]) * tanY - center[2]);
	CG_FatBoss_InspectHideArmEnd(&localHand, tanX, tanY, (const vec3_t *)points, numPoints, localOrigin);
	if (profile->stableFit)
	{
		for (i = 0; i < 3; i++)
		{
			fbInspect.frameCenterModel[i] = DotProduct(center, localHand.axis[i]);
			fbInspect.frameCenterCam[i]   = localOrigin[i] + center[i];
		}
		fbInspect.framed = qtrue;
	}

placed:
	VectorCopy(cg.refdef_current->vieworg, targetOrigin);
	for (i = 0; i < 3; i++)
	{
		VectorMA(targetOrigin, localOrigin[i] * projectionScale[i], cg.refdef_current->viewaxis[i], targetOrigin);
	}
	MatrixMultiply(localHand.axis, cg.refdef_current->viewaxis, targetAxis);
	if (profile->style == FB_STYLE_KNIFE)
	{
		CG_FatBoss_KnifeTwist(hand, targetOrigin, targetAxis);
	}
	return qtrue;
}

/**
 * @brief Turn the knife hand about the forearm axis through the wrist.
 *
 * The fit is made at no twist, so the forearm stays where it was framed and
 * the blade turns with the hand like a real wrist twist.
 */
static void CG_FatBoss_KnifeTwist(const refEntity_t *hand, vec3_t origin, vec3_t axis[3])
{
	const fbInspectProfile_t *profile = fbInspect.profile;
	orientation_t            tag;
	vec3_t                   modelOrigin, modelAxis[3], a, pivot, offset, turned[3];
	float                    angle, c, s, t, rot[3][3];
	int                      i, j;

	angle = DEG2RAD(CG_FatBoss_KnifeSpin());
	if (angle == 0.0f || trap_R_LerpTag(&tag, hand, "tag_weapon", 0) < 0)
	{
		return;
	}

	// the knife viewmodel hangs on tag_weapon: find the forearm axis in the world
	VectorCopy(origin, modelOrigin);
	for (i = 0; i < 3; i++)
	{
		VectorMA(modelOrigin, tag.origin[i], axis[i], modelOrigin);
	}
	MatrixMultiply(tag.axis, axis, modelAxis);
	VectorClear(a);
	VectorCopy(modelOrigin, pivot);
	for (i = 0; i < 3; i++)
	{
		VectorMA(a, profile->wristAxis[i], modelAxis[i], a);
		VectorMA(pivot, profile->wristPivot[i], modelAxis[i], pivot);
	}
	VectorNormalize(a);

	// rotation about the unit axis a (Rodrigues)
	c = cosf(angle);
	s = sinf(angle);
	t = 1.0f - c;
	rot[0][0] = t * a[0] * a[0] + c;        rot[0][1] = t * a[0] * a[1] - s * a[2]; rot[0][2] = t * a[0] * a[2] + s * a[1];
	rot[1][0] = t * a[0] * a[1] + s * a[2]; rot[1][1] = t * a[1] * a[1] + c;        rot[1][2] = t * a[1] * a[2] - s * a[0];
	rot[2][0] = t * a[0] * a[2] - s * a[1]; rot[2][1] = t * a[1] * a[2] + s * a[0]; rot[2][2] = t * a[2] * a[2] + c;

	for (i = 0; i < 3; i++)
	{
		for (j = 0; j < 3; j++)
		{
			turned[i][j] = DotProduct(rot[j], axis[i]);
		}
	}
	AxisCopy(turned, axis);
	VectorSubtract(origin, pivot, offset);
	for (j = 0; j < 3; j++)
	{
		origin[j] = pivot[j] + DotProduct(rot[j], offset);
	}
}

/**
 * @brief Blend from normal placement into a camera-relative inspection target.
 *
 * No camera, aiming, gameplay state, input or user cvar is modified. Normal gun
 * offsets and any incoming axis scale are smoothly removed only during inspect.
 */
void CG_FatBoss_ApplyInspect(refEntity_t *hand)
{
	float  fraction = CG_FatBoss_InspectFraction();
	float  scale[3], tanX, tanY;
	vec3_t targetOrigin, targetAxis[3], naturalAxis[3], projectionScale, localAxis;
	mat4_t naturalMatrix, targetMatrix;
	quat_t naturalQuat, targetQuat, blendedQuat;
	int    i, j;

	if (fraction <= 0.0f || !CG_FatBoss_InspectTarget(hand, targetOrigin, targetAxis))
	{
		return;
	}

	// quaternion interpolation avoids distorted or sheared axes during the turn
	AxisCopy(hand->axis, naturalAxis);
	for (i = 0; i < 3; i++)
	{
		scale[i] = VectorNormalize(naturalAxis[i]);
	}
	MatrixFromVectorsFLU(naturalMatrix, naturalAxis[0], naturalAxis[1], naturalAxis[2]);
	MatrixFromVectorsFLU(targetMatrix, targetAxis[0], targetAxis[1], targetAxis[2]);
	quat_from_mat4(naturalQuat, naturalMatrix);
	quat_from_mat4(targetQuat, targetMatrix);
	quat_slerp(naturalQuat, targetQuat, fraction, blendedQuat);
	quat_to_axis(blendedQuat, hand->axis);
	CG_FatBoss_InspectProjection(&tanX, &tanY, projectionScale);
	for (i = 0; i < 3; i++)
	{
		VectorScale(hand->axis[i], scale[i] + fraction * (1.0f - scale[i]), hand->axis[i]);
		for (j = 0; j < 3; j++)
		{
			localAxis[j] = DotProduct(hand->axis[i], cg.refdef_current->viewaxis[j])
			               * (1.0f + fraction * (projectionScale[j] - 1.0f));
		}
		VectorClear(hand->axis[i]);
		for (j = 0; j < 3; j++)
		{
			VectorMA(hand->axis[i], localAxis[j], cg.refdef_current->viewaxis[j], hand->axis[i]);
		}
		hand->origin[i] += fraction * (targetOrigin[i] - hand->origin[i]);
	}
	hand->nonNormalizedAxes = qtrue;
}

// support hands disappear halfway into the inspect and come back halfway out
#define FB_HIDE_FRACTION 0.5f

static qhandle_t fbOneHandSkins[ARRAY_LEN(fbInspectProfiles)][2];

static qboolean CG_FatBoss_Inspecting(int weaponNum)
{
	return fbInspect.active && fbInspect.profile && weaponNum == fbInspect.weapon;
}

/**
 * @brief First-person weapon part hidden while inspecting (the support hand).
 */
qboolean CG_FatBoss_HidePart(int weaponNum, int part)
{
	return CG_FatBoss_Inspecting(weaponNum) && (fbInspect.profile->hideParts & FB_PART(part))
	       && CG_FatBoss_InspectFraction() > FB_HIDE_FRACTION;
}

/**
 * @brief First-person main-model skin, swapped while inspecting to hide a support hand.
 */
qhandle_t CG_FatBoss_GunSkin(int weaponNum, int team, qhandle_t skin)
{
	qhandle_t oneHand;

	if (!CG_FatBoss_Inspecting(weaponNum) || CG_FatBoss_InspectFraction() <= FB_HIDE_FRACTION)
	{
		return skin;
	}
	oneHand = fbOneHandSkins[fbInspect.profile - fbInspectProfiles][team == TEAM_ALLIES ? 1 : 0];
	return oneHand ? oneHand : skin;
}

/*
 * Graffiti
 *
 * The server (fatboss.lua) checks the spray, picks the player's design and
 * sends "fbspray" to everyone. Each player owns at most one graffiti: a new
 * spray replaces the old one, a map restart clears them all. The image is
 * projected onto the world geometry once and redrawn every frame, so it does
 * not depend on cg_markTime and survives until it is replaced.
 */

#define FB_SPRAY_MAX_VERTS 256
#define FB_SPRAY_MAX_FRAGS 32

typedef struct
{
	qboolean active;
	qhandle_t shader;
	int numPolys;
	int polyVerts[FB_SPRAY_MAX_FRAGS];
	polyVert_t verts[FB_SPRAY_MAX_VERTS];
} fbSpray_t;

static fbSpray_t   fbSprays[MAX_CLIENTS];
static sfxHandle_t fbSpraySound;

/**
 * @brief Design names come from the server: only [a-z0-9_] reach a shader path.
 */
static qboolean CG_FatBoss_ValidDesign(const char *design)
{
	int i;

	for (i = 0; design[i]; i++)
	{
		if (i >= 32 || !((design[i] >= 'a' && design[i] <= 'z') || (design[i] >= '0' && design[i] <= '9') || design[i] == '_'))
		{
			return qfalse;
		}
	}
	return i > 0;
}

/**
 * @brief fbspray <client> <design> <x y z> <normal xyz> <up xyz> <radius> <sound 0|1>
 */
static void CG_FatBoss_ParseSpray(void)
{
	// the mark syscall writes five floats per point (xyz and a renderer UV pair)
	float          pointBuffer[FB_SPRAY_MAX_VERTS][5];
	markFragment_t fragments[FB_SPRAY_MAX_FRAGS];
	fbSpray_t      *spray;
	vec3_t         origin, normal, up, right, center, quad[4], projection, delta;
	char           design[64];
	int            clientNum, numFragments, i, j, k, first, numPoints;
	float          radius;
	qboolean       onPlane;
	static const float signs[4][2] = { { -1, -1 }, { -1, 1 }, { 1, 1 }, { 1, -1 } };

	if (trap_Argc() != 14)
	{
		return;
	}
	clientNum = Q_atoi(CG_Argv(1));
	Q_strncpyz(design, CG_Argv(2), sizeof(design));
	if (clientNum < 0 || clientNum >= MAX_CLIENTS || !CG_FatBoss_ValidDesign(design))
	{
		return;
	}
	for (i = 0; i < 3; i++)
	{
		origin[i] = Q_atof(CG_Argv(3 + i));
		normal[i] = Q_atof(CG_Argv(6 + i));
		up[i]     = Q_atof(CG_Argv(9 + i));
	}
	// the server shrinks the graffiti until all of it fits on the wall
	radius = Com_Clamp(8.0f, 48.0f, Q_atof(CG_Argv(12)));
	if (VectorNormalize(normal) < 0.5f)
	{
		return;
	}
	// keep up on the surface, then right completes the frame seen from the front
	VectorMA(up, -DotProduct(up, normal), normal, up);
	if (VectorNormalize(up) < 0.1f)
	{
		PerpendicularVector(up, normal);
	}
	CrossProduct(up, normal, right);
	VectorNormalize(right);

	spray         = &fbSprays[clientNum];
	spray->active = qfalse;

	// a square half a unit in front of the hit, projected 2 units back; a negative
	// fragment count selects the original mapping, so the UVs below stay upright
	VectorMA(origin, 0.5f, normal, center);
	VectorScale(normal, -2.0f, projection);
	for (i = 0; i < 4; i++)
	{
		VectorMA(center, signs[i][0] * radius, right, quad[i]);
		VectorMA(quad[i], signs[i][1] * radius, up, quad[i]);
	}
	numFragments = trap_CM_MarkFragments(4, (const vec3_t *)quad, projection, FB_SPRAY_MAX_VERTS,
	                                     &pointBuffer[0][0], -FB_SPRAY_MAX_FRAGS, fragments);

	spray->numPolys = 0;
	k               = 0;
	for (i = 0; i < numFragments && i < FB_SPRAY_MAX_FRAGS; i++)
	{
		first     = fragments[i].firstPoint;
		numPoints = fragments[i].numPoints;
		if (first < 0 || numPoints < 3 || numPoints > MAX_VERTS_ON_POLY || first + numPoints > FB_SPRAY_MAX_VERTS
		    || k + numPoints > FB_SPRAY_MAX_VERTS)
		{
			continue;
		}
		// stay on the same wall: uneven rock and trim stay in, a wall around a
		// corner or the far side of thin geometry does not
		{
			vec3_t e1, e2, faceNormal;

			VectorSubtract(pointBuffer[first + 1], pointBuffer[first], e1);
			VectorSubtract(pointBuffer[first + 2], pointBuffer[first], e2);
			CrossProduct(e1, e2, faceNormal);
			onPlane = VectorNormalize(faceNormal) > 0.0001f && Q_fabs(DotProduct(faceNormal, normal)) > 0.7f;
		}
		for (j = 0; onPlane && j < numPoints; j++)
		{
			VectorSubtract(pointBuffer[first + j], origin, delta);
			if (Q_fabs(DotProduct(delta, normal)) > 8.0f)
			{
				onPlane = qfalse;
			}
		}
		if (!onPlane)
		{
			continue;
		}
		for (j = 0; j < numPoints; j++)
		{
			polyVert_t *v = &spray->verts[k + j];

			// lift a hair off the surface; the shader's polygonOffset does the rest
			VectorMA(pointBuffer[first + j], 0.12f, normal, v->xyz);
			VectorSubtract(pointBuffer[first + j], origin, delta);
			v->st[0] = 0.5f + DotProduct(delta, right) / (2.0f * radius);
			v->st[1] = 0.5f - DotProduct(delta, up) / (2.0f * radius);
			// the client has no light sampling: a slightly dimmed paint does not glow in the dark
			v->modulate[0] = v->modulate[1] = v->modulate[2] = 210;
			v->modulate[3] = 255;
		}
		spray->polyVerts[spray->numPolys++] = numPoints;
		k                                  += numPoints;
	}
	spray->shader = trap_R_RegisterShader(va("fatboss/graffiti/%s", design));
	spray->active = spray->numPolys && spray->shader;
	CG_DPrintf("fbspray: client %i design %s fragments %i polys %i verts %i\n", clientNum, design, numFragments,
	           spray->numPolys, k);

	if (spray->active && Q_atoi(CG_Argv(13)) && fbSpraySound)
	{
		trap_S_StartSound(origin, ENTITYNUM_WORLD, CHAN_AUTO, fbSpraySound);
	}
}

/*
 * Weapon skins
 *
 * The server (fatboss.lua) sends every player's FatBoss loadout as
 *   fbskin <client> <knife> <colt> <luger> <thompson> <mp40> [<client> ...]
 * with a theme name or "-" per slot. The skins pk3 holds each theme as a 4k,
 * 2k and 1k texture; cg_fatboss_skins.inc (generated with them) says which
 * weapon model carries the gun texture. A model that is all gun gets a custom
 * shader, one with hands or sleeves in it gets a .skin file.
 *
 * Sizes: 4k for your own first-person weapon, 2k for the player you spectate,
 * 1k for everybody else's weapon in third person. Uploading a texture takes
 * width * height * 4 bytes of hunk temp memory, and running out of it drops
 * the player from the server, so a size only loads when the hunk has room;
 * otherwise the next smaller one does.
 */

#define FB_SKIN_SLOTS    5
#define FB_SKIN_TEXTURES 6

typedef struct
{
	const char *name;
	int textures;           ///< bit per texture the theme has
} fbSkinTheme_t;

typedef struct
{
	int weapon;
	int slot;
	int tex;
	int view;               ///< W_FP_MODEL or W_TP_MODEL
	int part;               ///< -1 for the weapon model itself
	const char *skin;       ///< .skin id for models with hands in them, NULL for a custom shader
	qboolean teamSkin;      ///< .skin comes per team (sleeves)
} fbSkinModel_t;

#include "cg_fatboss_skins.inc"

#define FB_SKIN_THEMES ((int)ARRAY_LEN(fbSkinThemes))
#define FB_SKIN_MODELS ((int)ARRAY_LEN(fbSkinModels))

typedef enum
{
	FB_RES_4K,
	FB_RES_2K,
	FB_RES_1K,
	FB_RES_COUNT
} fbSkinRes_t;

static const char *fbSkinResNames[FB_RES_COUNT] = { "4k", "2k", "1k" };

#define FB_SKIN_HUNK_MARGIN (16 * 1024 * 1024)

static int fbSkinLoadout[MAX_CLIENTS][FB_SKIN_SLOTS];                       ///< theme + 1, 0 = stock
static int fbSkinRow[WP_NUM_WEAPONS][W_NUM_TYPES][W_MAX_PARTS + 1];         ///< fbSkinModels index + 1
static int fbSkinWeaponSlot[WP_NUM_WEAPONS];                                ///< slot + 1
// registered handles; 0 not tried yet, -1 missing
static int fbSkinShaders[FB_SKIN_THEMES][FB_SKIN_TEXTURES][FB_RES_COUNT];
static int fbSkinFiles[FB_SKIN_MODELS][FB_SKIN_THEMES][FB_RES_COUNT][2];
// the size each (theme, texture, requested size) really got
static signed char fbSkinResUsed[FB_SKIN_THEMES][FB_SKIN_TEXTURES][FB_RES_COUNT];

static int CG_FatBoss_ThemeIndex(const char *name)
{
	int i;

	for (i = 0; i < FB_SKIN_THEMES; i++)
	{
		if (!Q_stricmp(name, fbSkinThemes[i].name))
		{
			return i;
		}
	}
	return -1;
}

/**
 * @brief Largest size up to res whose upload fits in the hunk right now.
 */
static int CG_FatBoss_SkinRes(int theme, int tex, int res)
{
	char    buf[32];
	int     megs, used, r;
	int64_t room;

	if (fbSkinResUsed[theme][tex][res])
	{
		return fbSkinResUsed[theme][tex][res] - 1;
	}
	trap_Cvar_VariableStringBuffer("com_hunkMegs", buf, sizeof(buf));
	megs = Q_atoi(buf);
	trap_Cvar_VariableStringBuffer("com_hunkused", buf, sizeof(buf));
	used = Q_atoi(buf);
	room = (int64_t)megs * 1024 * 1024 - used - FB_SKIN_HUNK_MARGIN;
	for (r = res; r < FB_RES_1K; r++)
	{
		// 4 bytes a pixel; each size down has a quarter of the pixels
		if (((int64_t)fbSkinTexPixels[tex] * 4 >> (2 * r)) <= room)
		{
			break;
		}
	}
	if (r != res)
	{
		CG_Printf("FatBoss: %s %s skin at %s, the hunk has %i MB free (raise com_hunkMegs for %s)\n",
		          fbSkinThemes[theme].name, fbSkinTexNames[tex], fbSkinResNames[r], (int)(room / (1024 * 1024)),
		          fbSkinResNames[res]);
	}
	fbSkinResUsed[theme][tex][res] = (signed char)(r + 1);
	return r;
}

static qhandle_t CG_FatBoss_SkinShader(int theme, int tex, int res)
{
	int *h;

	res = CG_FatBoss_SkinRes(theme, tex, res);
	h   = &fbSkinShaders[theme][tex][res];
	if (!*h)
	{
		*h = trap_R_RegisterShader(va("fatboss/skins/%s/%s_%s", fbSkinThemes[theme].name, fbSkinTexNames[tex], fbSkinResNames[res]));
		if (!*h)
		{
			*h = -1;
		}
	}
	return *h > 0 ? *h : 0;
}

static qhandle_t CG_FatBoss_SkinFile(int row, int theme, int res, int team)
{
	const fbSkinModel_t *m = &fbSkinModels[row];
	int                 t  = m->teamSkin && team == TEAM_ALLIES ? 1 : 0;
	int                 *h;

	res = m->view == W_TP_MODEL ? FB_RES_1K : CG_FatBoss_SkinRes(theme, m->tex, res);
	h   = &fbSkinFiles[row][theme][res][t];
	if (!*h)
	{
		*h = trap_R_RegisterSkin(va("models/fatboss/skins/%s/%s_%s%s.skin", fbSkinThemes[theme].name, m->skin,
		                            fbSkinResNames[res], m->teamSkin ? (t ? "_allied" : "_axis") : ""));
		if (!*h)
		{
			*h = -1;
		}
	}
	return *h > 0 ? *h : 0;
}

/**
 * @brief Puts the player's skin on one weapon model (main model or a part) before it is drawn.
 */
void CG_FatBoss_WeaponSkin(refEntity_t *re, int clientNum, int weaponNum, int view, int part, int team, int powerups)
{
	const fbSkinModel_t *m;
	int                 row, theme, res;
	qhandle_t           h;

	if (weaponNum <= WP_NONE || weaponNum >= WP_NUM_WEAPONS || !fbSkinWeaponSlot[weaponNum])
	{
		return;
	}
	// no stock code gives these weapons a custom shader, and parts share one
	// refEntity: clear what the previous part got
	re->customShader = 0;
	if (clientNum < 0 || clientNum >= MAX_CLIENTS || view < 0 || view >= W_NUM_TYPES || part < -1 || part >= W_MAX_PARTS)
	{
		return;
	}
	row = fbSkinRow[weaponNum][view][part + 1];
	if (!row)
	{
		return;
	}
	m     = &fbSkinModels[row - 1];
	theme = fbSkinLoadout[clientNum][m->slot] - 1;
	if (theme < 0 || !(fbSkinThemes[theme].textures & (1 << m->tex)))
	{
		return;
	}
	// a disguised covert op must not give himself away by his weapon
	if (view == W_TP_MODEL && (powerups & (1 << PW_OPS_DISGUISED)))
	{
		return;
	}
	if (view == W_TP_MODEL)
	{
		res = FB_RES_1K;
	}
	else
	{
		res = clientNum == cg.clientNum ? FB_RES_4K : FB_RES_2K;
	}
	if (m->skin)
	{
		h = CG_FatBoss_SkinFile(row - 1, theme, res, team);
		if (h)
		{
			re->customSkin = h;
		}
	}
	else
	{
		h = CG_FatBoss_SkinShader(theme, m->tex, res);
		if (h)
		{
			re->customShader = h;
		}
	}
}

/**
 * @brief Loads a player's skins when they arrive, not when the weapon is first drawn:
 * your own first-person ones for your team's weapons, and everybody's third-person ones.
 */
static void CG_FatBoss_PreloadSkins(int clientNum)
{
	static const int axisWeapons[]   = { WP_KNIFE, WP_LUGER, WP_MP40 };
	static const int alliedWeapons[] = { WP_KNIFE_KABAR, WP_COLT, WP_THOMPSON };
	int              i, theme, team = cgs.clientinfo[clientNum].team;

	for (i = 0; i < FB_SKIN_MODELS; i++)
	{
		const fbSkinModel_t *m = &fbSkinModels[i];

		theme = fbSkinLoadout[clientNum][m->slot] - 1;
		if (theme < 0 || !(fbSkinThemes[theme].textures & (1 << m->tex)) || m->view != W_TP_MODEL)
		{
			continue;
		}
		if (m->skin)
		{
			CG_FatBoss_SkinFile(i, theme, FB_RES_1K, team);
		}
		else
		{
			CG_FatBoss_SkinShader(theme, m->tex, FB_RES_1K);
		}
	}
	if (clientNum != cg.clientNum || (team != TEAM_AXIS && team != TEAM_ALLIES))
	{
		return;
	}
	for (i = 0; i < 3; i++)
	{
		int weapon = team == TEAM_AXIS ? axisWeapons[i] : alliedWeapons[i];
		int row    = 0, p;

		// the knife's gun texture sits on a part, not on the main model
		for (p = 0; p <= W_MAX_PARTS && !row; p++)
		{
			row = fbSkinRow[weapon][W_FP_MODEL][p];
		}
		if (!row)
		{
			continue;
		}
		theme = fbSkinLoadout[clientNum][fbSkinModels[row - 1].slot] - 1;
		if (theme >= 0 && (fbSkinThemes[theme].textures & (1 << fbSkinModels[row - 1].tex)))
		{
			CG_FatBoss_SkinShader(theme, fbSkinModels[row - 1].tex, FB_RES_4K);
		}
	}
}

/**
 * @brief fbskin <client> <knife> <colt> <luger> <thompson> <mp40> [<client> ...]
 */
static void CG_FatBoss_ParseSkins(void)
{
	int argc = trap_Argc(), i, s, clientNum;

	for (i = 1; i + FB_SKIN_SLOTS < argc; i += FB_SKIN_SLOTS + 1)
	{
		clientNum = Q_atoi(CG_Argv(i));
		if (clientNum < 0 || clientNum >= MAX_CLIENTS)
		{
			continue;
		}
		for (s = 0; s < FB_SKIN_SLOTS; s++)
		{
			fbSkinLoadout[clientNum][s] = CG_FatBoss_ThemeIndex(CG_Argv(i + 1 + s)) + 1;
		}
		CG_FatBoss_PreloadSkins(clientNum);
	}
}

static void CG_FatBoss_InitSkins(void)
{
	int i;

	Com_Memset(fbSkinLoadout, 0, sizeof(fbSkinLoadout));
	Com_Memset(fbSkinRow, 0, sizeof(fbSkinRow));
	Com_Memset(fbSkinWeaponSlot, 0, sizeof(fbSkinWeaponSlot));
	Com_Memset(fbSkinShaders, 0, sizeof(fbSkinShaders));
	Com_Memset(fbSkinFiles, 0, sizeof(fbSkinFiles));
	Com_Memset(fbSkinResUsed, 0, sizeof(fbSkinResUsed));
	for (i = 0; i < FB_SKIN_MODELS; i++)
	{
		const fbSkinModel_t *m = &fbSkinModels[i];

		fbSkinRow[m->weapon][m->view][m->part + 1] = i + 1;
		fbSkinWeaponSlot[m->weapon]                 = m->slot + 1;
	}
}

/**
 * @brief fb_skins: who wears what, and at which size it loaded here.
 */
void CG_FatBoss_Skins_f(void)
{
	int i, s, t, r, any = 0;

	for (i = 0; i < MAX_CLIENTS; i++)
	{
		char line[256] = "";

		for (s = 0; s < FB_SKIN_SLOTS; s++)
		{
			if (fbSkinLoadout[i][s])
			{
				Q_strcat(line, sizeof(line), va(" %s=%s", fbSkinSlotNames[s], fbSkinThemes[fbSkinLoadout[i][s] - 1].name));
			}
		}
		if (line[0])
		{
			CG_Printf("%2i %s^7:%s\n", i, cgs.clientinfo[i].infoValid ? cgs.clientinfo[i].name : "?", line);
			any = 1;
		}
	}
	if (!any)
	{
		CG_Printf("FatBoss: nobody here wears a weapon skin\n");
	}
	for (i = 0; i < FB_SKIN_THEMES; i++)
	{
		for (t = 0; t < FB_SKIN_TEXTURES; t++)
		{
			for (r = 0; r < FB_RES_COUNT; r++)
			{
				if (fbSkinShaders[i][t][r])
				{
					CG_Printf("  loaded %s/%s_%s%s\n", fbSkinThemes[i].name, fbSkinTexNames[t], fbSkinResNames[r],
					          fbSkinShaders[i][t][r] < 0 ? " ^1missing" : "");
				}
			}
		}
	}
}

/**
 * @brief Server commands for FatBoss; returns qtrue when the command was ours.
 */
qboolean CG_FatBoss_ServerCommand(const char *cmd)
{
	if (!Q_stricmp(cmd, "fbskin"))
	{
		CG_FatBoss_ParseSkins();
		return qtrue;
	}
	if (!Q_stricmp(cmd, "fbspray"))
	{
		CG_FatBoss_ParseSpray();
		return qtrue;
	}
	if (!Q_stricmp(cmd, "fbspray_clear"))
	{
		int clientNum = Q_atoi(CG_Argv(1));

		if (clientNum >= 0 && clientNum < MAX_CLIENTS)
		{
			fbSprays[clientNum].active = qfalse;
		}
		return qtrue;
	}
	return qfalse;
}

void CG_FatBoss_AddSprays(void)
{
	int i, j, k;

	for (i = 0; i < MAX_CLIENTS; i++)
	{
		if (!fbSprays[i].active)
		{
			continue;
		}
		for (j = 0, k = 0; j < fbSprays[i].numPolys; k += fbSprays[i].polyVerts[j], j++)
		{
			trap_R_AddPolyToScene(fbSprays[i].shader, fbSprays[i].polyVerts[j], &fbSprays[i].verts[k]);
		}
	}
}

void CG_FatBoss_ClearSprays(void)
{
	Com_Memset(fbSprays, 0, sizeof(fbSprays));
}

void CG_FatBoss_Version_f(void)
{
	CG_Printf("FatBoss cgame %s on %s %s\n", FATBOSS_CGAME_VERSION, MODNAME, ETLEGACY_VERSION);
}

void CG_FatBoss_Init(void)
{
	int i, j;

	Com_Memset(&fbInspect, 0, sizeof(fbInspect));
	CG_FatBoss_ClearSprays();
	CG_FatBoss_InitSkins();
	fbSpraySound = trap_S_RegisterSound("sound/fatboss/spray.wav", qfalse);
	trap_Cvar_Register(&fb_inspectshots, "fb_inspectshots", "0", CVAR_TEMP);
	for (i = 0; i < (int)ARRAY_LEN(fbInspectProfiles); i++)
	{
		for (j = 0; j < 2; j++)
		{
			fbOneHandSkins[i][j] = fbInspectProfiles[i].oneHandSkin[j] ? trap_R_RegisterSkin(fbInspectProfiles[i].oneHandSkin[j]) : 0;
		}
	}
	Com_Printf(S_COLOR_YELLOW "FatBoss cgame %s loaded\n", FATBOSS_CGAME_VERSION);
}
