"""The skins without the moving shine (fb_shine 0, cgame b16).

The B shine is the studio stage of every skin shader (build_skins.py): the studio image, mapped by the view
(tcGen environment) and masked by the gloss map, so the highlights slide over the gun as it moves. Some players
will not like it on some skins, so the cgame can swap each skin shader for its flat twin: the same stages with the
studio stage turned into a still one of the studio image's mean brightness, so the gun keeps its overall shade.

Reads the skins pk3's shader scripts (fatboss/pk3-skins/scripts, the build of build_skins.py) and writes
fatboss/pk3/scripts/fatboss_flat.shader (the cgame pk3): fbf/<theme>/<tex>_<res> for every
fatboss/skins/<theme>/<tex>_<res> that has a studio stage. Run it again whenever the skins are built again.

    py fatboss/skins/build_flat.py
"""
import glob
import os
import re
import sys

import numpy as np
from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import build_skins as bs  # noqa: E402

OUT = os.path.join(bs.REPO, "fatboss", "pk3", "scripts", "fatboss_flat.shader")


def blocks(text):
    """(name, body) of every shader of a script, body the text between its outer braces."""
    text = re.sub(r"//[^\n]*", "", text)
    out, i = [], 0
    while True:
        m = re.compile(r"\s*([^\s{}]+)\s*\{").match(text, i)
        if not m:
            break
        depth, j = 1, m.end()
        while depth:
            depth += {"{": 1, "}": -1}.get(text[j], 0)
            j += 1
        out.append((m.group(1), text[m.end():j - 1]))
        i = j
    return out


def main():
    studio = os.path.join(bs.OUT, "models", "fatboss", "skins", "studio.jpg")
    rgb = np.asarray(Image.open(studio).convert("RGB"), np.float64) / 255
    k = rgb.mean(axis=(0, 1))
    still = ("\t{\n\t\tmap $whiteimage\n\t\trgbGen const ( %.3f %.3f %.3f )\n\t\tblendFunc GL_DST_COLOR GL_ZERO\n\t}" % tuple(k))
    lines = ["// FatBoss skins without the moving shine (fb_shine 0) - generated by fatboss/skins/build_flat.py, do not edit",
             f"// the studio stage is still: the mean of studio.jpg, {k[0]:.3f} {k[1]:.3f} {k[2]:.3f}", ""]
    count = 0
    for path in sorted(glob.glob(os.path.join(bs.OUT, "scripts", "fatboss_skins_*.shader"))):
        for name, body in blocks(open(path, encoding="utf-8").read()):
            if not name.startswith("fatboss/skins/"):
                continue
            stages = re.findall(r"\{[^{}]*\}", body)
            head = re.sub(r"\{[^{}]*\}", "", body).strip()
            if not any("tcGen environment" in s for s in stages):
                continue
            flat = [still if "tcGen environment" in s else "\t" + s.strip().replace("\n\t\t", "\n\t\t").replace("\n\t}", "\n\t}")
                    for s in stages]
            flat_name = "fbf/" + name[len("fatboss/skins/"):]
            if len(flat_name) >= bs.MAX_QPATH:
                raise SystemExit(f"{flat_name}: too long for the engine")
            head_lines = "".join(f"\t{h.strip()}\n" for h in head.splitlines() if h.strip())
            lines.append(f"{flat_name}\n{{\n{head_lines}" + "\n".join(flat) + "\n}\n")
            count += 1
    with open(OUT, "w", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"{count} flat shaders -> {OUT}")


if __name__ == "__main__":
    main()
