// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/fade/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/fade/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/colt.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.33 0.33 0.33 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/fade/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/fade/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/colt.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.33 0.33 0.33 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/fade/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/fade/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/luger.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.33 0.33 0.33 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/fade/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/fade/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/luger.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.33 0.33 0.33 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/fade/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/fade/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/thompson.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.33 0.33 0.33 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/fade/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/fade/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/thompson.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.33 0.33 0.33 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/fade/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/fade/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/mp40.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.33 0.33 0.33 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/fade/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/fade/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/mp40.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.33 0.33 0.33 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/fade/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/fade/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/knife.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.33 0.33 0.33 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/fade/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/fade/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/knife.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.33 0.33 0.33 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/fade/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/fade/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/kabar.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.33 0.33 0.33 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/fade/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/fade/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/kabar.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.33 0.33 0.33 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
