// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/sale/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sale/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sale/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.08 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
