// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/sticker_bomb/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/sticker_bomb/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/sticker_bomb/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
