// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/plasma/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/plasma/colt_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/plasma/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/plasma/colt_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/plasma/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/plasma/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/plasma/luger_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/plasma/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/plasma/luger_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/plasma/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/plasma/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/plasma/thompson_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/plasma/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/plasma/thompson_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/plasma/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/plasma/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/plasma/mp40_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/plasma/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/plasma/mp40_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/plasma/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/plasma/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/plasma/knife_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/plasma/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/plasma/knife_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/plasma/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/plasma/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/plasma/kabar_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/plasma/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/plasma/kabar_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/plasma/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/plasma/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.30 0.45 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
