// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/gold/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
