// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/skill_issue/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/skill_issue/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/skill_issue/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.14 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
