// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/gold/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/gold/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/gold/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.85 0.75 0.50 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/neon/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/colt_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/colt_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/neon/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/luger_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/luger_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/neon/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/thompson_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/thompson_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/neon/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/mp40_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/mp40_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/neon/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/knife_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/knife_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/neon/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/kabar_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/kabar_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/damascus/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/damascus/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.70 0.72 0.76 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/damascus/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/damascus/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.70 0.72 0.76 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/damascus/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/damascus/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.70 0.72 0.76 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/damascus/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/damascus/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.70 0.72 0.76 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/damascus/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/damascus/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.70 0.72 0.76 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/damascus/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/damascus/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.70 0.72 0.76 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/defender/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/defender/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/defender/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/defender/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/defender/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/defender/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/wut/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/wut/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/wut/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/wut/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/wut/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/wut/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
