// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/wut/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/wut/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/wut/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/wut/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/wut/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/wut/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
