// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/defender/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/defender/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/colt.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/defender/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/defender/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/colt.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen lightingDiffuse
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
