// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/cyber/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/cyber/colt_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/cyber/colt_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/colt.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/cyber/colt_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/cyber/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/cyber/colt_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/cyber/colt_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/colt.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/cyber/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/cyber/luger_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/cyber/luger_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/luger.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/cyber/luger_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/cyber/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/cyber/luger_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/cyber/luger_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/luger.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/cyber/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/cyber/thompson_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/cyber/thompson_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/thompson.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/cyber/thompson_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/cyber/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/cyber/thompson_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/cyber/thompson_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/thompson.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/cyber/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/cyber/mp40_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/cyber/mp40_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/mp40.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/cyber/mp40_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/cyber/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/cyber/mp40_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/cyber/mp40_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/mp40.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/cyber/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/cyber/knife_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/cyber/knife_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/knife.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/cyber/knife_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/cyber/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/cyber/knife_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/cyber/knife_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/knife.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/cyber/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/cyber/kabar_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/cyber/kabar_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/kabar.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/cyber/kabar_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/cyber/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/cyber/kabar_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/cyber/kabar_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/kabar.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}
