// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/caution_noob/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/caution_noob/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/caution_noob/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.12 0.12 0.12 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
