// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/neon/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/colt_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/colt_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/neon/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/luger_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/luger_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/neon/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/thompson_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/thompson_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/neon/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/mp40_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/mp40_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/neon/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/knife_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/knife_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/neon/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/kabar_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
	{
		map models/fatboss/skins/neon/kabar_glow.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen identity
	}
}

fatboss/skins/neon/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/neon/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.30 0.34 0.40 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
