// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/connection_interrupted/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/connection_interrupted/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/connection_interrupted/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.08 0.08 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
