// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/polska/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/polska/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/polska/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.35 0.35 0.35 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
