// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/damascus/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/damascus/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.70 0.72 0.76 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/damascus/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/damascus/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.70 0.72 0.76 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/damascus/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/damascus/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.70 0.72 0.76 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/damascus/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/damascus/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.70 0.72 0.76 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/damascus/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/damascus/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.70 0.72 0.76 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/damascus/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/damascus/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.70 0.72 0.76 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
