// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/airstrike/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/airstrike/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/airstrike/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.25 0.22 0.30 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
