// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/wut/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/thompson_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/wut/thompson_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/thompson.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/wut/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/thompson_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/wut/thompson_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/thompson.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/wut/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/kabar_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/wut/kabar_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/kabar.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/wut/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/wut/kabar_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/wut/kabar_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/kabar.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}
