// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/camo/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/colt_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/colt_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/colt_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/colt_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/luger_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/luger_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/luger_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/luger_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/thompson_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/thompson_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/thompson_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/thompson_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/mp40_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/mp40_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/mp40_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/mp40_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/knife_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/knife_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/knife_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/knife_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/kabar_4k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/kabar_2k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/kabar_2k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}

fatboss/skins/camo/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/camo/kabar_1k.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/env.jpg
		rgbGen const ( 0.10 0.10 0.10 )
		tcGen environment
		blendFunc GL_DST_COLOR GL_ONE
	}
}
