// FatBoss weapon skins - generated by fatboss/skins/build_skins.py, do not edit

fatboss/skins/aurora/colt_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/aurora/colt_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/aurora/colt_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/colt.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/aurora/colt_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/aurora/colt_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/aurora/colt_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/colt.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/aurora/luger_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/aurora/luger_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/aurora/luger_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/luger.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/aurora/luger_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/aurora/luger_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/aurora/luger_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/luger.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/aurora/thompson_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/aurora/thompson_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/aurora/thompson_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/thompson.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/aurora/thompson_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/aurora/thompson_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/aurora/thompson_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/thompson.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/aurora/mp40_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/aurora/mp40_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/aurora/mp40_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/mp40.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/aurora/mp40_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/aurora/mp40_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/aurora/mp40_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/mp40.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/aurora/knife_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/aurora/knife_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/aurora/knife_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/knife.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/aurora/knife_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/aurora/knife_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/aurora/knife_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/knife.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/aurora/kabar_4k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/aurora/kabar_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/aurora/kabar_4k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/kabar.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}

fatboss/skins/aurora/kabar_1k
{
	nopicmip
	nocompress
	{
		map models/fatboss/skins/aurora/kabar_gloss.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fatboss/skins/studio.jpg
		tcGen environment
		blendFunc GL_DST_COLOR GL_ZERO
	}
	{
		map models/fatboss/skins/aurora/kabar_1k.jpg
		blendFunc GL_ONE GL_ONE
		rgbGen lightingDiffuse
	}
	{
		map fbs/wear/kabar.png
		alphaFunc GE128
		alphaGen entity
		rgbGen lightingDiffuse
	}
}
