// FatBoss punishment prop (cgame b17) - generated by fatboss/skins/build_prop.py, do not edit

models/fbprop/pink
{
	nopicmip
	{
		map models/fbprop/pink.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fbprop/shine.jpg
		tcGen environment
		blendFunc GL_ONE GL_ONE
		rgbGen const ( 0.55 0.5 0.52 )
	}
}

models/fbprop/steel
{
	nopicmip
	{
		map models/fbprop/steel.jpg
		rgbGen lightingDiffuse
	}
	{
		map models/fbprop/shine.jpg
		tcGen environment
		blendFunc GL_ONE GL_ONE
		rgbGen const ( 0.6 0.6 0.6 )
	}
}
