// FatBoss decals - generated by fatboss/skins/build_decals.py, do not edit

// the decal models' own shader: the cgame always draws them with a customShader
fbd/decal
{
	surfaceparm nodraw
	surfaceparm nomarks
}

fbd/s/gg
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/gg.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/ez
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/ez.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/noob
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/noob.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/nice_try
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/nice_try.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/gibbed
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/gibbed.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/poland_et
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/poland_et.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/cloudy
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/cloudy.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/kurwa_mac
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/kurwa_mac.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/get_rekt
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/get_rekt.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/lagging
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/lagging.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/skill_issue
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/skill_issue.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/skill_404
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/skill_404.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/rip_bozo
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/rip_bozo.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/jebac_axis
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/jebac_axis.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/jebac_allies
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/jebac_allies.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/sprzedam_opla
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/sprzedam_opla.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/nastepny_przystanek
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/nastepny_przystanek.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/next_stop
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/next_stop.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/wut_1112
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/wut_1112.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/spawn_camper
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/spawn_camper.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/arty_incoming
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/arty_incoming.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/dyno_planted
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/dyno_planted.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/headshot
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/headshot.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/one_tap
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/one_tap.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/rage_quit
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/rage_quit.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/skill_diff
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/skill_diff.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/cry_more
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/cry_more.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/brb_coffee
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/brb_coffee.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/panzer_noob
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/panzer_noob.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/potato_aim
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/potato_aim.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/toaster_pc
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/toaster_pc.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/s/honk
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stickers/honk.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/plate
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stattrak/plate.png
		blendFunc blend
		rgbGen lightingDiffuse
	}
}

fbd/digit0
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stattrak/0.png
		blendFunc blend
		rgbGen identity
	}
}

fbd/digit1
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stattrak/1.png
		blendFunc blend
		rgbGen identity
	}
}

fbd/digit2
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stattrak/2.png
		blendFunc blend
		rgbGen identity
	}
}

fbd/digit3
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stattrak/3.png
		blendFunc blend
		rgbGen identity
	}
}

fbd/digit4
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stattrak/4.png
		blendFunc blend
		rgbGen identity
	}
}

fbd/digit5
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stattrak/5.png
		blendFunc blend
		rgbGen identity
	}
}

fbd/digit6
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stattrak/6.png
		blendFunc blend
		rgbGen identity
	}
}

fbd/digit7
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stattrak/7.png
		blendFunc blend
		rgbGen identity
	}
}

fbd/digit8
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stattrak/8.png
		blendFunc blend
		rgbGen identity
	}
}

fbd/digit9
{
	nopicmip
	polygonOffset
	sort decal
	{
		clampmap fatboss/stattrak/9.png
		blendFunc blend
		rgbGen identity
	}
}
